### ISSUE TITLE
Hidden tab index in IE

### ISSUE THREAD

**Issue by ryandang** [pablojim/highcharts-ng#154]
In IE, There is a hidden tabindex for pie charts and bar graph. When the users use the keyboard to navigate through the website content, they will have to tab through the charts in IE.

**Comment by irumgodil** [comment]
is there a way around this?

**Comment by pablojim** [comment]
Not sure what the issue is.

**Comment by irumgodil** [comment]
The issue is that when you embed HighChart in IE and then keep tabbing, there is an invisible tab point. I have debugged and found the issue has to do with the SVG chart element that honors the "focusable" property instead of tabIndex. In my code I am dynamically retrieving this element and have set the property to false, but ideally it should not be present on the chart at all.
