### ISSUE TITLE
Support for heatmaps

### ISSUE THREAD

**Issue by kylebuckingham** [pablojim/highcharts-ng#276]
I've attempted to load the default highcharts heatmap example but I am receiving two errors: 
1. If I move the 'chart:' object into options, I get the highcharts Error 17:
http://www.highcharts.com/errors/17
2. If I don't do #1, the chart draws but there are no squares.
 
![image](https://cloud.githubusercontent.com/assets/1248512/6217024/67bc9784-b5c4-11e4-8412-197107fc4b16.png)

I've included the heatmap.js module and there are no other errors (other than the ones above) in the console.

link to default example:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/

**Comment by pablojim** [comment]
Could you make a jsfiddle (even a broken one!)?

**Comment by kylebuckingham** [comment]
I could try to make one later tonight that uses highcharts-ng but in the meantime, its the exact same configuration from the default example:

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/

I’ve been able to get other charts to work in my app (spline). I think its specific to the heat map

- Kyle


On Feb 16, 2015, at 10:17 AM, Barry Fitzgerald <notifications@github.com<mailto:notifications@github.com>> wrote:

Could you make a jsfiddle (even a broken one!)?

**Comment by kylebuckingham** [comment]
Ugh found the problem: needed to add the http://code.highcharts.com/modules/heatmap.js to dependencies. Works like a charm now :p

**Comment by CWSites** [comment]
@kylebuckingham can you post your solution? I included the highcharts heatmaps to my bower.json dependencies and ran bower update and bower install. It seems to have installed correctly because now it's in my components directory with all of my other dependencies.

### Bower.json
`"highcharts-heatmaps": "http://code.highcharts.com/modules/heatmap.js",`

I also updated my require_config.js path to point to the index.js file that is inside components/highcharts-heatmaps directory. Finally I am requiring it on the page where I setup the controller.

### chart.js 
`require('highcharts-heatmaps');`

I've verified that it is loading on the page, however I'm still getting the Highcharts error 17 along with this JS error on the page.

`Uncaught TypeError: undefined is not a functionindex.js:17
(anonymous function)highcharts.src.js:1005 win.HighchartsAdapter.win.HighchartsAdapter.$.init.each.Array.forEach.iindex.js:17
(anonymous function)index.js:22
(anonymous function)`

Any help that you or anyone else would be greatly appreciated!

**Comment by kylebradshaw** [comment]
hey @kylebuckingham 

I am having a hard time getting the heatmap to work as well with this directive, however, your solution of adding the heatmap library as an external resource in your fiddle wasn't a solution.

I forked your fiddle and added the heatmap expecting it to work (I was in the same boat using the directive but only getting that janky line chart).

Here is my forked fiddle.
http://jsfiddle.net/somedirection/gahpdxm2/2/

For example. If I added the 
http://code.highcharts.com/modules/heatmap.js as an external resource, nothing

BUT if I add the exporting module
http://code.highcharts.com/modules/exporting.js
I do see that it was picked up.

@pablojim  are heatmaps supported? Do you have a working fiddle of the highcharts-ng rendering a heatmap? I'm not able to get it to work.

@kylebuckingham if you got a fix what was it?

**Comment by kylebuckingham** [comment]
I believe you need to move your chart and color axis into an "options" object:

http://jsfiddle.net/ygb80j1z/

**Comment by sakilamsandhya** [comment]
``

**Comment by SunBurst** [comment]
The fiddle above didn't work due to outdated library references. I replaced the concerned ones with more recent versions and forked it: http://jsfiddle.net/60xajuLr/

It seems like the issue is back or am I missing something?
