### ISSUE TITLE
Unable to get 'shared' ToolTip working

### ISSUE THREAD

**Issue by boje** [pablojim/highcharts-ng#317]
Hi
Shared tooltip do not work or is ignored.
<code>tooltip: { 
     shared: true 
}</code>
http://api.highcharts.com/highcharts#tooltip.shared

Example.
https://jsfiddle.net/r88yszk0/16/

![capture](https://cloud.githubusercontent.com/assets/706785/7472460/15b34c92-f333-11e4-96e3-4595022f214c.PNG)

**Comment by jonasbru** [comment]
Hey, because I was just looking for a way of changing dynamically the shared attribute of the tooltip and arrived here, I'm able to answer your question : 

You're not passing in a proper way the options of the graph. They're split in two, ones go into the root object, the others into an "options" object. Read the main page or the project, it's all explained.

And here you have an updated fiddle with a shared tooltip : http://jsfiddle.net/Hjdnw/1207/

**Comment by pablojim** [comment]
Thanks @jonasbru

**Comment by boje** [comment]
That was quick help.. Thanks @jonasbru

**Comment by chsipeng** [comment]
Thanks @jonasbru
