### ISSUE TITLE
Chart print width

### ISSUE THREAD

**Issue by PDSBGreg** [pablojim/highcharts-ng#324]
I have 3 charts (side by side in a DIV with flex layout="row"). From the attached screen shot, you can see that charts on screen show 6 columns on the X axis. When printed, only the first 3 are shown.

Kind of like the reflow on the chart isn't called when printing occurs. Is there anything that can fix this?
![screen shot 2015-05-13 at 3 30 45 pm](https://cloud.githubusercontent.com/assets/10424675/7619275/859fbe52-f985-11e4-97df-3bbf65ad8f1f.png)

**Comment by agoodwin** [comment]
I have a similar issue with a chart in a 12 column wide Bootstrap div, which also seems to boil down to the chart not resizing upon print. I get a very wide chart, which causes the rest of the content on the page to shrink.

I'll try to make some progress on this on my own.

**Comment by mattsaddo** [comment]
having a similar issue here as well +1.

**Comment by agoodwin** [comment]
I couldn't find any proper fix for this. The charts are resized through JavaScript, not simply CSS, and so it doesn't look like there's any way to have the print view affect the sizing.

I have only bothered to support Chrome, so this is probably different for other browsers, but I have a (very) rough workaround. I'm not very happy with it, but in case its helpful to you guys I'll explain my approach.

Basically the chart won't resize when printing, but printing itself seems to cause the page to be something like a constant 700px wide. Therefore everything else in the page is resizing for that 700 pixels through css, except the chart which stays at the same width and height as it already was. So in my css I have a print media query which sets the body of the page to have a width that nicely matches the chart when printing.

This only works because I assume to know the chart's width (because typically a browser window is big enough that the chart is always at its maximum size). if I want to support printing when the chart is smaller than normal, for example when the browser window is resized to half the screen, all I can do is have my print button on the page (that calls window.print) also resize the chart first. That would allow the chart to be set to a known size before printing, but only if the print button in the page is used.

Basically if you have the chart at a known size, you can set the rest of the page to match it in the css using a print media query. After doing that I use the zoom CSS descriptor on the document body (also in the print media query) to scale the whole page to fit the paper (at a known paper size).

It's really horrible and not general at all but its the best I could do in the time I had.

**Comment by mattsaddo** [comment]
Thanks. Been researching this a bit and i think that you add a listener on the print media. When that activates reflow high charts. Haven't had a chance to test this yet but might work.
```
var mediaQueryList = window.matchMedia('print');
mediaQueryList.addListener(function(mql) {
    if (mql.matches) {
        //trigger highcharts reflow
    } 
 });
```

**Comment by pelizza** [comment]
Hi @agoodwin,

I'm facing this same problem here, and now I got why that happens, after your explanation.
Any news about the solution? I'll try something here and post back in the case I got some interesting results.

Thanks.

**Comment by agoodwin** [comment]
Nope, I have gone no further on this other than what I explained in my previous post.

Basically my chart has a maximum width of something like 1140px. So when the print view resizes the viewport to a width of around 700px, the following css takes effect:

```
@media print {
	body {
		width: 1180px;
		zoom: 0.60;
	}
}
```

The 1180px width of the body ensures that the content on the page is the appropriate width for the fixed chart size of 1140px, including a bit of padding. Then the zoom of 60% scales that 1180px so that it's about right for the 700px print width. Like I said it's really horrible but for my purposes it gets the job done.

**Comment by pelizza** [comment]
Thanks, I'll try something like that. Until now, I got no better solution :(
