### ISSUE TITLE
chart destroy

### ISSUE THREAD

**Issue by praswebdev** [pablojim/highcharts-ng#334]
i am using highcharts in two places in our application and we have two tabs. When i click on one tab , the first grpah loads and on click of second tab the second graphs loads.
When i switch the tabs, the respective controller is created and the chart is initialized.
But we found that the Highcharts maintains an array of charts, that is incremented on every load of the view. 
Do we need to destroy the charts when we switch the tabs? or will the directive takes care of it?
i see the following code in highcharts-ng
        scope.$on('$destroy', function () {
          if (chart) {
            chart.destroy();
            $timeout(function () {
              element.remove();
            }, 0);
          }
        });

**Comment by ubenzer** [comment]
As far as I see from the code,

directive initializes a chart, there are n highcharts are on memory if there are n directive on the page. (whether they are visible or they on the invisible tab is irrelevant) 

The relevant Highcharts chart is destoryed when directive is destroyed. For example if you put directive into an `ng-if` and set condition to something false, it will be destroyed.

If you have a lot of tabs with a lot of charts, maybe you should add an `ng-if` condition to each chart, checking if that tab is active or not. In that way you'll always have one chart. Otherwise, they'll be rendered but invisible.

**Please note that** I am not the developer of this library, I am just a user of this library who inspected code a little bit.

**Comment by praswebdev** [comment]
Thanks for your comment :-)
