### ISSUE TITLE
Data binding works fine but get error: Invalid value for <text> attribute x="NaN..."

### ISSUE THREAD

**Issue by JoachimR** [pablojim/highcharts-ng#344]
This problem has been fixed before as I have seen from other issues but it still gives me troubles with version 0.0.8

Have a look in your browser console when running the follwing fiddle: 

http://jsfiddle.net/35xqueef/

**Comment by jaimeguaman** [comment]
I think it's not a ng-highcharts problem, instead Highcharts itself or your config object with an element config property inside your graph.

specifically the problem is with your x axis title align.

this is what triggers the error
```svg
<text x="NaN" zIndex="7" text-anchor="undefined" transform="translate(0,0)" class=" highcharts-xaxis-title" style="color:#707070;fill:#707070;" visibility="visible" y="644">S</text> 
```

in your ng-higcharts config object you have:
```javascript
            xAxis: {
                currentMin: 1,
                currentMax: 100,
                title: {
                    text: 'S',
                    align: "right"
                },
                labels: {
                    formatter: function () {
                        return (this.value + " units");
                    }
                }
            },
```
I removed the `align`property and the error disappeared
http://jsfiddle.net/v152o77a/

**Comment by JoachimR** [comment]
thank you very much @jaimeguaman ! 

I used the wrong value for align because I used the wrong documentation: http://api.highcharts.com/highcharts#title.align

but the value needs to be 'low', 'middle' or 'high' as described here: http://api.highcharts.com/highcharts#xAxis.title
