### ISSUE TITLE
TypeError: Cannot assign to read only property 'getHighcharts' of chartConfig0

### ISSUE THREAD

**Issue by GaurangGhinaiya** [pablojim/highcharts-ng#380]
i am trying to pass dynamic config name like this
```
<div class="form-group col-sm-12" ng-repeat="arr in finalAry">
        <highchart id="chart1" config="arr.name"></highchart>
    </div>
```

Here `arr.name` is dyanmic name in finalAry.

When i use this i got following error in console

`TypeError: Cannot assign to read only property 'getHighcharts' of chartConfig0`

**Comment by jaimeguaman** [comment]
could you please upload an example to jsfiddle or similar in order to have more data about your problem?

**Comment by GaurangGhinaiya** [comment]
Here i am using static name
[FIDDLE1] (http://jsfiddle.net/7cAq3/679/)

in this fiddle i try same thing using dynamic name using ng-repeat
[FIDDLE2] (http://jsfiddle.net/7cAq3/680/).

see the error in console window of FIDDLE2

**Comment by jaimeguaman** [comment]
@GaurangGhinaiya Oh I see

the problem is that `config` is receiving a `String` instead of an `Object` because of your angular expression `'chartConfig'+$index` 

try this instead:
http://jsfiddle.net/e6rxqu3r/

if you're concerned about `.push()`performance, you can do this as well
http://jsfiddle.net/6o3rhdb7/
