### ISSUE TITLE
Boost module doesn't seem to be working.

### ISSUE THREAD

**Issue by laureanoarcanio** [pablojim/highcharts-ng#391]
Hi, have you tried it with the boost module ? I have added the boost module and it doesn't render it using the canvas/image as it should. Any pointing directions ? Thanks

**Comment by pablojim** [comment]
I have never used the Boost module. Maybe add a jsfiddle showing the issue?

**Comment by githistory** [comment]
same issue

**Comment by mathiasconradt** [comment]
Wondering why this issue is closed, has it been resolved? Anyway, I am also having problems with the boost module. Need to check if it's a highchart or a highcharts-ng issue.

http://jsfiddle.net/j950np50/25/

You can see in my script, I enabled the "boost" in the chart configuration.

```
    boost: {
      useGPUTranslations: true,
      seriesThreshold: 0,
      boostThreshold: 0
    },
```

and the default dashStyle of a series graph should be dash (not solid):

```
      series: {
        animation: false,      
        dashStyle: 'dash',
```

because I have the above in my chart configuration. The dashstyle is solid though when boost is enabled, it is only dashed when I remove the boost.

A second issue: in my script, I am changing the series dashstyle and markers after 1 second.

```
    series.update({       
      marker: {
        symbol: 'triangle',
      },
      dashStyle: 'dot'
    }, true); 
```

The dashstyle should be "dot" and the markers should be triangles. It works fine without boost, but with boost enabled, the dashStyle does not change, and the marker triangles only show when the user hovers over a point, but in the normal state, the point markers are still shown as circles. This should not be the case.
