### ISSUE TITLE
highcharts-ng grows but doesn't shrink in flexbox

### ISSUE THREAD

**Issue by hoolymama** [pablojim/highcharts-ng#398]
I'm trying to put a highchart in a flexbox container. The chart grows with the container just fine, but it doesn't shrink when the container shrinks.

Here's a plunkr to illustrate.
http://plnkr.co/edit/azlhAiTXDtPrXbaMYNes?p=preview
If you open the embedded view you'll notice when you make the window wider, both charts reflow to fit. But when you make it narrower, the top chart (in a flexbox), remains unchanged. Seems odd that it works one way and not the other.

I put in the reflow button to broadcast the reflow event but it seems to have no effect.

I realize there are other similar issues regarding reflow, but the solutions don't seem to solve this particular case. Any ideas? If not, I'll use floats.

Thanks

**Comment by cyril-blanco** [comment]
I guess it's too late, but I ran into the same kind of problem while rendering a highcharts-ng into a flexbox container. I resolved it by setting "flex: 1" on the div replacing the highchart directive.

<pre>
.container {
  > div {
    flex: 1;
  }
}
</pre>

**Comment by hoolymama** [comment]
Thanks for this!

Actually I [posted to Stackoverflow](http://stackoverflow.com/questions/33291605/highcharts-ng-grows-but-doesnt-shrink-in-flexbox) after posting here and someone answered and made a [plunkr that fixed it](http://plnkr.co/edit/l1xc7BTQKnKI2dPygNfj?p=preview). I think the fix is similar to yours.

Cheers

**Comment by cyril-blanco** [comment]
Well, actually this plunker doesn't show the next issue I had with height because the chart has a fixed height. I ended up fixing my problem with the following code:

<pre>
.container {
  > div {
    height: 100%;
    width: 100%;
  }
}
</pre>

I think the underlying problem of most issues related to chart size is the div replacing the highchart directive: if it is not properly sized (from a JS point of view) when the chart renders, it will fail to set the size correctly. So, the fix probably depends on your particular layout/css.
