### ISSUE TITLE
Highcharts expects point configuration to be numbers or arrays in turbo mode

### ISSUE THREAD

**Issue by sajeetharan** [pablojim/highcharts-ng#432]
I have developed a dynamic chart generation applicaiton using highcharts-ng , it works well for data below 1000, but when it likes to render for datas above 1000, it returns this error.

Highcharts expects point configuration to be numbers or arrays in turbo mode

I know this can be fixed with normal highcharts, but with highcharts-ng how can i fix this? where to add the turboThreshold option?

i can post the necessary config if required!

 scope.chartConfView = {
        "options": {
            "chart": {
                "type": "area"
            },
            "plotOptions": {
                "turboThreshold": 3000,
                "series": {
                    "stacking": ""
                }
            }
        },
        "series": [{
            "name": "View Count",
            "data": [],
            "id": "series-0",
            "type": "area",
            "dashStyle": "ShortDashDot",
            "connectNulls": false,
            "color": "#FF5722"
        }],
        "title": {
            "text": "Page Views"
        },
        "credits": {
            "enabled": false
        },
        "loading": false,
        "xAxis": {
            "type": "datetime",
            "currentMin": 0
        },
        "yAxis": {
            "min": 0
        }
    };

**Comment by roydondsouza** [comment]
Hi @sajeetharan ,

You cannot use `turboThreshold` directly inside `plotOptions`. 


You can use turboThreshold in the following way :

- plotOptions.[chartType].turboThreshold
- series.[chartType].turboThreshold

See the screenshots and the[ official documentation](http://api.highcharts.com/highcharts#plotOptions.series.turboThreshold):

<img width="1259" alt="screen shot 2016-01-28 at 10 23 57 am" src="https://cloud.githubusercontent.com/assets/4233828/12635472/a72ad3fe-c5a9-11e5-8ad8-135be8c4555f.png">


In your case, since you are using series type, 

You can use it inside series:

```
"series": [{
"turboThreshold": 3000,
"name": "View Count",
"data": [],
"id": "series-0",
"type": "area",
"dashStyle": "ShortDashDot",
"connectNulls": false,
"color": "#FF5722"
}],

```

Or inside plotOption.series:

```
"plotOptions": {
"series": {
"turboThreshold": 3000,
"stacking": ""
}
}
```

Hope this helps!

**Comment by sajeetharan** [comment]
Hi @roydondsouza 

It dint seem to work .

**Comment by roydondsouza** [comment]
@sajeetharan can you create a fiddle and share the link?

**Comment by sajeetharan** [comment]
It worked when i added to series. Thank you
